### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Shuailong** [kentonl/neuralccg#1]
When I run the setup.sh, there are errors shown below:

```
ERROR: /home/lsl/.cache/bazel/_bazel_lsl/56c7e50a00d6cbebb347ec04f008972d/external/cnn/BUILD.bazel:3:1: no such package '@eigen//': Missing unknown aaaa8c33025952bc8ef8c5c946fe8ab9cf45bf5d and referenced by '@cnn//:cnn-lib'.
ERROR: Analysis of target '//neuralccg:libdecoder.so' failed; build aborted.
INFO: Elapsed time: 111.077s
cp: cannot stat 'bazel-bin/neuralccg/libdecoder.so': No such file or directory
cp: cannot stat 'bazel-bin/neuralccg/libdecoder.so': No such file or directory

```

I guess it is compatibility issues. Could you give any suggestions on how to resolve this?

Thank you in advance!

**Comment by lalchand-pandia** [comment]
Hi,
how did you resolve this issue?

**Comment by Shuailong** [comment]
@lalchand-pandia I think I just use the newer commitID of cnn

**Comment by lalchand-pandia** [comment]
Hi,
I guess cnn comes with bazel. So did you use newer version of bazel?

**Comment by kentonl** [comment]
It looks like newer versions of bazel didn't like the way I was including eigen. 1f05312b207700fe6103577aae2359858d3a12c9 fixes this.
